const fs = require('fs');
const lines = [
  "import { Route } from '@angular/router';",
  "",
  "function comingSoon(path, title, heading) {",
  "  return {",
  "    path,",
  "    loadComponent: () => import('./features/coming-soon/coming-soon').then(m => m.ComingSoon),",
  "    title,",
  "    data: { heading },",
  "  };",
  "}",
  "",
  "export const routes = [",
  "  {",
  "    path: '',",
  "    loadComponent: () => import('./features/home/home').then(m => m.Home),",
  "    title: 'A Diamond Worth Remembering',",
  "  },",
  "  {",
  "    path: 'diamonds',",
  "    loadComponent: () => import('./features/diamonds/listing/diamond-listing').then(m => m.DiamondListing),",
  "    title: 'Certified Diamonds',",
  "  },",
  "  {",
  "    path: 'diamonds/:slug',",
  "    loadComponent: () => import('./features/diamonds/detail/diamond-detail').then(m => m.DiamondDetail),",
  "    title: 'Diamond',",
  "  },",
  "  {",
  "    path: 'jewellery',",
  "    loadComponent: () => import('./features/jewellery/jewellery-listing/jewellery-listing').then(m => m.JewelleryListing),",
  "    title: 'Diamond Jewellery',",
  "  },",
  "  {",
  "    path: 'collections',",
  "    loadComponent: () => import('./features/collections/collections').then(m => m.Collections),",
  "    title: 'Collections',",
  "  },",
  "  {",
  "    path: 'build-your-ring',",
  "    loadComponent: () => import('./features/build-ring/build-ring').then(m => m.BuildRing),",
  "    title: 'Build Your Ring',",
  "  },",
  "  {",
  "    path: 'learn',",
  "    loadComponent: () => import('./features/education/learn-landing/learn-landing').then(m => m.LearnLanding),",
  "    title: 'Learn',",
  "  },",
  "  {",
  "    path: 'learn/four-cs',",
  "    loadComponent: () => import('./features/education/four-cs/four-cs').then(m => m.FourCs),",
  "    title: 'The 4Cs',",
  "  },",
  "  {",
  "    path: 'learn/natural-vs-lab-grown',",
  "    loadComponent: () => import('./features/education/natural-vs-lab-grown/natural-vs-lab-grown').then(m => m.NaturalVsLabGrown),",
  "    title: 'Natural vs Lab-Grown Diamonds',",
  "  },",
  "  {",
  "    path: 'learn/certification',",
  "    loadComponent: () => import('./features/education/certification/certification').then(m => m.Certification),",
  "    title: 'Certification',",
  "  },",
  "  comingSoon('learn/care', 'Diamond Care', 'Diamond Care'),",
  "];",
];
fs.writeFileSync('src/app/app.routes.ts', lines.join('\n') + '\n');
console.log('done');
